export const Strings = {
  app: {
    name: '배드민턴 코트',
  },
  auth: {
    login: '로그인',
    register: '회원가입',
    phone: '전화번호',
    password: '비밀번호',
    name: '이름',
    phonePlaceholder: '01012345678',
    passwordPlaceholder: '6자 이상',
    namePlaceholder: '이름을 입력하세요',
    loginButton: '로그인',
    registerButton: '회원가입',
    goToRegister: '계정이 없으신가요? 회원가입',
    goToLogin: '이미 계정이 있으신가요? 로그인',
    logout: '로그아웃',
  },
  facility: {
    title: '시설',
    list: '시설 목록',
    noFacilities: '등록된 시설이 없습니다',
    board: '현황판',
    courts: '코트',
    select: '체육관 선택',
    selectDescription: '이용할 체육관을 선택하세요',
    searchPlaceholder: '체육관 이름 또는 주소로 검색',
    listView: '목록',
    mapView: '지도',
    change: '체육관 변경',
    changeDescription: '다른 체육관으로 변경합니다',
    distance: '거리',
    noLocation: '위치 정보를 사용할 수 없습니다',
    locationPermission: '위치 권한이 필요합니다',
    info: '시설 정보',
    operatingHours: '운영 시간',
    sessionStarted: '운영 시작',
    courtStatus: '코트 현황',
    location: '위치',
  },
  court: {
    status: {
      EMPTY: '비어있음',
      IN_USE: '사용 중',
      MAINTENANCE: '점검 중',
    },
    gameType: {
      DOUBLES: '복식',
      LESSON: '레슨',
    },
  },
  checkin: {
    title: '체크인',
    scanQR: 'QR 스캔',
    checkedIn: '체크인 중',
    checkout: '체크아웃',
    notCheckedIn: '체크인하지 않았습니다',
    banner: '체크인하면 순번 등록이 가능합니다',
    readOnlyNotice: '읽기 전용 모드',
  },
  club: {
    title: '모임',
    create: '모임 만들기',
    join: '초대코드로 가입',
    inviteCode: '초대코드',
    members: '멤버',
    noClubs: '가입된 모임이 없습니다',
    role: {
      LEADER: '대표',
      STAFF: '운영진',
      MEMBER: '회원',
    },
    session: '모임 활동',
    sessionStart: '모임 시작',
    sessionEnd: '모임 종료',
    sessionActive: '모임 진행중',
    sessionManage: '모임 관리',
    sessionHint: '체크인된 시설에서 모임을 시작합니다',
  },
  turn: {
    title: '순번',
    register: '순번 등록',
    cancel: '순번 취소',
    complete: '게임 종료',
    requeue: '다시 줄서기',
    requeueConfirm: '다시 줄서기 하시겠습니까?',
    requeueDesc: '현재 순번을 취소하고 대기열 끝으로 이동합니다.',
    waiting: '대기 중',
    playing: '게임 중',
    completed: '완료',
    cancelled: '취소됨',
    status: {
      WAITING: '대기 중',
      PLAYING: '게임 중',
      COMPLETED: '완료',
      CANCELLED: '취소됨',
    },
    indicator: '순번',
    noTurn: '등록된 순번이 없습니다',
    selectPlayers: '멤버 선택',
    searchPlayers: '이름으로 검색',
    waitingQueue: '대기열',
    nowPlaying: '현재 게임',
  },
  game: {
    complete: '게임 종료',
    status: {
      IN_PROGRESS: '진행 중',
      COMPLETED: '완료',
      CANCELLED: '취소',
    },
  },
  mygame: {
    title: '내 순번',
    noGame: '등록된 순번이 없습니다',
    inProgress: '게임 중',
  },
  tabs: {
    board: '현황판',
    activity: '내 활동',
    settings: '설정',
  },
  activity: {
    title: '내 활동',
    todayHistory: '오늘 완료된 게임',
    recruitmentActivity: '모집 참여',
    clubActivity: '모임 활동',
    noActivity: '아직 활동이 없습니다',
    estimatedWait: '예상 대기',
    nextTurn: '다음 순번입니다',
  },
  settings: {
    title: '설정',
    facility: '시설',
    checkinStatus: '체크인',
    clubs: '모임',
    notifications: '알림',
    tvDisplay: 'TV 디스플레이 모드',
    tvDisplayDesc: '대형 화면용 코트 현황 표시',
    profile: '프로필',
    profileEdit: '프로필 편집',
    admin: '관리자',
    adminDesc: '운영, 게임 편성, 코트 관리',
    version: '버전',
  },
  player: {
    status: {
      AVAILABLE: '대기',
      IN_TURN: '순번중',
      RESTING: '휴식',
    },
    rest: '휴식',
    available: '대기',
    toggleRest: '휴식 전환',
    toggleAvailable: '대기 복귀',
    skillLevel: {
      BEGINNER: '초급',
      INTERMEDIATE: '중급',
      ADVANCED: '상급',
      EXPERT: '고급',
    },
  },
  capacity: {
    available: '대기',
    inTurn: '게임중',
    resting: '휴식',
  },
  timer: {
    warning: '게임 종료 임박!',
    expired: '시간 초과',
    remaining: '남은 시간',
  },
  recruitment: {
    title: '조 모집',
    create: '모집하기',
    join: '참여하기',
    leave: '탈퇴',
    register: '순번 등록',
    cancel: '취소',
    recruiting: '모집중',
    full: '모집완료',
    registered: '등록완료',
    cancelled: '취소됨',
    expired: '만료',
    status: {
      RECRUITING: '모집중',
      FULL: '모집완료',
      REGISTERED: '등록완료',
      CANCELLED: '취소됨',
      EXPIRED: '만료',
    },
    noRecruitments: '활성 모집이 없습니다',
  },
  rotation: {
    title: '게임 편성',
    generate: '편성하기',
    start: '시작',
    cancel: '취소',
    regenerate: '재편성',
    status: {
      DRAFT: '편성됨',
      ACTIVE: '진행중',
      COMPLETED: '완료',
      CANCELLED: '취소됨',
    },
  },
  admin: {
    title: '관리자',
    dashboard: '관리자',
    sessionOpen: '운영 시작',
    sessionClose: '운영 종료',
    sessionOpenConfirm: '운영을 시작하시겠습니까?',
    sessionOpenConfirmDesc: '운영을 시작하면 회원들이 체크인하고 순번을 등록할 수 있습니다.',
    courtManagement: '코트 관리',
    quickActions: '빠른 실행',
    todayStats: '오늘 통계',
    totalGames: '총 게임',
    avgWaitTime: '평균 대기',
    peakPlayers: '최대 인원',
    currentPlayers: '현재 인원',
    capacityOverview: '인원 현황',
    viewRotation: '편성 보기',
    selectAll: '전체 선택',
    deselectAll: '선택 해제',
    filterAll: '전체',
    roundLabel: '라운드',
    currentRound: '현재',
    completed: '완료',
    inProgress: '진행중',
    pending: '대기',
    swapPlayers: '선수 교체',
    swapInstruction: '교체할 선수를 선택하세요',
    roundMatrix: '라운드 x 코트 배치표',
    participantStats: '참가자 통계',
    adminMenu: '시설 관리',
  },
  notification: {
    title: '알림',
    empty: '알림이 없습니다',
    markRead: '읽음 처리',
    markAllRead: '모두 읽음',
    unreadCount: '개의 읽지 않은 알림',
    emptyDesc: '순번 등록, 게임 시작 등의 알림이 여기에 표시됩니다',
  },
  common: {
    loading: '로딩 중...',
    error: '오류가 발생했습니다',
    retry: '다시 시도',
    confirm: '확인',
    cancel: '취소',
    save: '저장',
    delete: '삭제',
  },
};
