export const Strings = {
  app: {
    name: '배드민턴 코트',
  },
  auth: {
    login: '로그인',
    register: '회원가입',
    phone: '전화번호',
    password: '비밀번호',
    name: '이름',
    phonePlaceholder: '01012345678',
    passwordPlaceholder: '6자 이상',
    namePlaceholder: '이름을 입력하세요',
    loginButton: '로그인',
    registerButton: '회원가입',
    goToRegister: '계정이 없으신가요? 회원가입',
    goToLogin: '이미 계정이 있으신가요? 로그인',
    logout: '로그아웃',
  },
  facility: {
    title: '시설',
    list: '시설 목록',
    noFacilities: '등록된 시설이 없습니다',
    board: '현황판',
    courts: '코트',
  },
  court: {
    status: {
      EMPTY: '비어있음',
      HELD: '홀드',
      IN_GAME: '게임 중',
      MAINTENANCE: '점검 중',
    },
  },
  checkin: {
    title: '체크인',
    scanQR: 'QR 스캔',
    checkedIn: '체크인 중',
    checkout: '체크아웃',
    notCheckedIn: '체크인하지 않았습니다',
  },
  club: {
    title: '모임',
    create: '모임 만들기',
    join: '초대코드로 가입',
    inviteCode: '초대코드',
    members: '멤버',
    noClubs: '가입된 모임이 없습니다',
  },
  hold: {
    create: '코트 홀드',
    release: '홀드 해제',
    active: '활성',
    grabSlots: '슬롯 먹기',
  },
  queue: {
    title: '대기열',
    join: '다음 차례 걸기',
    leave: '대기 취소',
    accept: '수락',
    myPosition: '내 순서',
    waiting: '대기 중',
    pendingAccept: '수락 대기',
    empty: '대기열이 비어있습니다',
    currentHolder: '현재 홀드',
    countdown: '남은 시간',
    slotStatus: '슬롯',
    queueBadge: 'Q',
  },
  mygame: {
    title: '내 게임',
    noGame: '배정된 게임이 없습니다',
    waitingAssignment: '편성 대기',
    scheduled: '예정됨',
    called: '호출됨',
    inProgress: '진행 중',
    confirmEntry: '입장 확인',
  },
  game: {
    lineup: '라인업',
    addGame: '게임 추가',
    call: '호출',
    accept: '수락',
    decline: '거절',
    start: '게임 시작',
    complete: '게임 종료',
    replace: '선수 교체',
    status: {
      WAITING: '대기',
      CALLING: '호출 중',
      CONFIRMED: '확정',
      IN_PROGRESS: '진행 중',
      COMPLETED: '완료',
      CANCELLED: '취소',
    },
    callStatus: {
      PENDING: '대기',
      ACCEPTED: '수락',
      DECLINED: '거절',
      NO_SHOW: '노쇼',
      REPLACED: '교체됨',
    },
  },
  common: {
    loading: '로딩 중...',
    error: '오류가 발생했습니다',
    retry: '다시 시도',
    confirm: '확인',
    cancel: '취소',
    save: '저장',
    delete: '삭제',
  },
};
